openapi: 3.0.0
info:
  title: Student Management API
  version: 1.0.0
  description: API documentation for a simple web application that allows users to manage Student entities, including storing and retrieving student data in a SQLite database.
  contact:
    name: Support
    email: support@example.com
servers:
  - url: http://localhost:5000/api/v1
    description: Development server

paths:
  /students:
    get:
      summary: Retrieve a list of students
      responses:
        '200':
          description: A list of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
    post:
      summary: Create a new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the student
                  example: "John Doe"
      responses:
        '201':
          description: Student created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "E001: Name is required"

  /students/{id}:
    get:
      summary: Retrieve a specific student by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the student to retrieve
      responses:
        '200':
          description: A student object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '404':
          description: Student not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "E002: Student not found"
    put:
      summary: Update an existing student
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the student to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The new name of the student
                  example: "Jane Doe"
      responses:
        '200':
          description: Student updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "E001: Name is required"
        '404':
          description: Student not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "E002: Student not found"
    delete:
      summary: Delete a specific student by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the student to delete
      responses:
        '204':
          description: Student deleted successfully
        '404':
          description: Student not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "E002: Student not found"

components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier for the student
          example: 1
        name:
          type: string
          description: The name of the student
          example: "John Doe"