from marshmallow import Schema, fields, validate

class StudentSchema(Schema):
    """Schema for validating and serializing student data."""

    id = fields.Int(dump_only=True)  # ID is generated by the database
    name = fields.Str(required=True, validate=validate.Length(min=1, error="Name is required."))  
    # Validate that the name is a non-empty string