"""
Main Streamlit UI for BAE Managed System.
Auto-generated by BAE Framework - provides navigation to all entity management pages.
"""

import streamlit as st
import importlib
import sys
from pathlib import Path

# Configure page
st.set_page_config(
    page_title="BAE Framework Demo",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="expanded"
)

def main():
    """Main Streamlit application."""
    st.title("🎓 BAE Framework Demo")
    st.markdown("**Auto-generated system for managing multiple business entities**")

    # Sidebar navigation
    st.sidebar.title("📋 Entity Management")
    st.sidebar.markdown("Select an entity to manage:")

    # Get available entities
    available_entities = get_available_entities()

    if not available_entities:
        st.warning("⚠️ No entities have been generated yet. Use the BAE framework to generate your first entity.")
        st.info("Example: Run the BAE system with a request like 'Create a system to manage students'")
        return

    # Entity selection
    selected_entity = st.sidebar.selectbox(
        "Choose Entity:",
        available_entities,
        format_func=lambda x: x.replace("_", " ").title()
    )

    # Load and display entity management page
    if selected_entity:
        load_entity_page(selected_entity)

    # System information in sidebar
    st.sidebar.markdown("---")
    st.sidebar.markdown("### 🤖 System Information")
    st.sidebar.info(f"**Entities**: {len(available_entities)}")
    st.sidebar.info("**Generated by**: BAE Framework")

def get_available_entities():
    """Get list of available entities based on generated pages."""
    entities = []
    pages_path = Path(__file__).parent / "pages"

    if pages_path.exists():
        for page_file in pages_path.glob("*_management.py"):
            entity_name = page_file.stem.replace("_management", "")
            entities.append(entity_name)

    return entities

def load_entity_page(entity_name):
    """Dynamically load entity management page."""
    try:
        # Add pages directory to Python path
        pages_path = Path(__file__).parent / "pages"
        if str(pages_path) not in sys.path:
            sys.path.insert(0, str(pages_path))

        module_name = f"{entity_name}_management"

        # Import the entity management module
        if module_name in sys.modules:
            # Reload if already imported (for hot reload)
            importlib.reload(sys.modules[module_name])
            module = sys.modules[module_name]
        else:
            module = importlib.import_module(module_name)

        # Call the main function if it exists
        if hasattr(module, "main"):
            module.main()
        elif hasattr(module, "show_entity_management"):
            module.show_entity_management()
        else:
            st.error(f"❌ No main() or show_entity_management() function found in {module_name}")

    except Exception as e:
        st.error(f"❌ Failed to load {entity_name} management page: {str(e)}")
        st.info("This usually means the entity page hasn't been generated yet.")

if __name__ == "__main__":
    main()
