openapi: 3.0.0
info:
  title: Student API
  version: 1.0.0
paths:
  /students:
    post:
      summary: Create a new student record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the student
                  example: John Doe
                email:
                  type: string
                  description: The email address of the student
                  example: john.doe@example.com
                  format: email
              required:
                - name
                - email
      responses:
        '201':
          description: Student created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Student created successfully.
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: E001
                      message:
                        type: string
                        example: Email field is required.
    get:
      summary: Retrieve all student records
      responses:
        '200':
          description: A list of student records
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: John Doe
                    email:
                      type: string
                      example: john.doe@example.com