"""
Main FastAPI application for BAE Managed System.
Auto-generated by BAE Framework - contains all entity routes.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import importlib
import logging
from pathlib import Path

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Create FastAPI app
app = FastAPI(
    title="BAE Managed Academic System",
    description="Auto-generated academic management system with multiple entities",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc"
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    """Root endpoint with system information."""
    return {
        "message": "BAE Managed Academic System",
        "description": "Auto-generated system managing multiple business entities",
        "version": "1.0.0",
        "entities": get_available_entities(),
        "docs": "/docs"
    }

@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {"status": "healthy", "system": "BAE Managed System"}

def get_available_entities():
    """Get list of available entities based on generated routes."""
    entities = []
    routes_path = Path(__file__).parent / "routes"

    if routes_path.exists():
        for route_file in routes_path.glob("*_routes.py"):
            entity_name = route_file.stem.replace("_routes", "")
            entities.append(entity_name)

    return entities

def load_all_routes():
    """Dynamically load all available entity routes."""
    routes_path = Path(__file__).parent / "routes"

    if not routes_path.exists():
        logger.warning("Routes directory not found")
        return

    for route_file in routes_path.glob("*_routes.py"):
        try:
            module_name = f"app.routes.{route_file.stem}"
            module = importlib.import_module(module_name)

            if hasattr(module, "router"):
                app.include_router(module.router)
                logger.debug(f"✅ Loaded routes from {module_name}")
            else:
                logger.warning(f"⚠️  No router found in {module_name}")

        except Exception as e:
            logger.error(f"❌ Failed to load {route_file}: {str(e)}")

# Load all available routes
load_all_routes()

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=True)
